// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using innogotchi_api.Data;

#nullable disable

namespace innogotchi_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230501115509_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("innogotchi_api.Models.Collaboration", b =>
                {
                    b.Property<string>("FarmName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FarmName", "UserEmail");

                    b.HasIndex("UserEmail");

                    b.ToTable("Collaborations");
                });

            modelBuilder.Entity("innogotchi_api.Models.Farm", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("innogotchi_api.Models.FeedingAndQuenching", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FeedingPeriod")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InnogotchiName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("QuenchingPeriod")
                        .HasColumnType("int");

                    b.Property<DateTime>("QuenchingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnhappyDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InnogotchiName");

                    b.ToTable("FeedingsAndQuenchings");
                });

            modelBuilder.Entity("innogotchi_api.Models.Innogotchi", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FarmName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("FarmName");

                    b.ToTable("Innogotchis");
                });

            modelBuilder.Entity("innogotchi_api.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FarmName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.HasIndex("FarmName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("innogotchi_api.Models.Collaboration", b =>
                {
                    b.HasOne("innogotchi_api.Models.Farm", "Farm")
                        .WithMany("Collaborations")
                        .HasForeignKey("FarmName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("innogotchi_api.Models.User", "User")
                        .WithMany("Collaborations")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("innogotchi_api.Models.FeedingAndQuenching", b =>
                {
                    b.HasOne("innogotchi_api.Models.Innogotchi", null)
                        .WithMany("FeedingAndQuenchings")
                        .HasForeignKey("InnogotchiName");
                });

            modelBuilder.Entity("innogotchi_api.Models.Innogotchi", b =>
                {
                    b.HasOne("innogotchi_api.Models.Farm", null)
                        .WithMany("Innogotchis")
                        .HasForeignKey("FarmName");
                });

            modelBuilder.Entity("innogotchi_api.Models.User", b =>
                {
                    b.HasOne("innogotchi_api.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmName");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("innogotchi_api.Models.Farm", b =>
                {
                    b.Navigation("Collaborations");

                    b.Navigation("Innogotchis");
                });

            modelBuilder.Entity("innogotchi_api.Models.Innogotchi", b =>
                {
                    b.Navigation("FeedingAndQuenchings");
                });

            modelBuilder.Entity("innogotchi_api.Models.User", b =>
                {
                    b.Navigation("Collaborations");
                });
#pragma warning restore 612, 618
        }
    }
}
